In [2]:
import sys
sys.path.append("..")
import cv2
import numpy as np
from cactus.face.detection import detector
from cactus.processing.video import to_frames, folder_to_frames
from PIL import Image

In [ ]:
folder_to_frames("../videos/", "../frames", 0.5)
dnn_detector = detector("haar")
faces = dnn_detector.to_face("../frames", "../dataset")

Converting jerson's videos into frames
Converting jerson's videos into frames
Converting jerson's videos into frames
Converting angel's videos into frames
Converting angel's videos into frames
Converting angel's videos into frames
Converting frank's videos into frames
Converting martin's videos into frames
Converting martin's videos into frames
Converting martin's videos into frames
Converting Lab's videos into frames
Converting Lab's videos into frames
Converting manu's videos into frames
Converting manu's videos into frames
Converting manu's videos into frames
Converting cristian's videos into frames
Using haar method
Detecting jerson's faces
Saved ../dataset
Saved ../dataset/train/jerson/2019-06-18 23:10:01.8984892019-06-18 23:17:50.907238__.jpg
Saved ../dataset
Saved ../dataset/train/jerson/2019-06-18 23:10:04.1205612019-06-18 23:17:50.922882__.jpg
Saved ../dataset
Saved ../dataset/train/jerson/2019-06-18 23:10:02.1202652019-06-18 23:17:50.937004__.jpg
Saved ../dataset
Saved ../dat

Saved ../dataset/test/jerson/2019-06-18 23:10:02.4921572019-06-18 23:17:51.930642__.jpg
Saved ../dataset
Saved ../dataset/test/jerson/2019-06-18 23:10:04.7851862019-06-18 23:17:51.946463__.jpg
Saved ../dataset
Saved ../dataset/test/jerson/2019-06-18 23:10:02.7153022019-06-18 23:17:51.961508__.jpg
Saved ../dataset
Saved ../dataset/test/jerson/2019-06-18 23:10:04.4810762019-06-18 23:17:51.978429__.jpg
Saved ../dataset
Saved ../dataset/test/jerson/2019-06-18 23:10:04.2020672019-06-18 23:17:51.995113__.jpg
Saved ../dataset
Saved ../dataset/test/jerson/2019-06-18 23:10:04.6377712019-06-18 23:17:52.009664__.jpg
Saved ../dataset
Saved ../dataset/test/jerson/2019-06-18 23:10:03.7933292019-06-18 23:17:52.023955__.jpg
Saved ../dataset
Saved ../dataset/test/jerson/2019-06-18 23:10:02.0245742019-06-18 23:17:52.036541__.jpg
Saved ../dataset
Saved ../dataset/test/jerson/2019-06-18 23:10:03.7699732019-06-18 23:17:52.050486__.jpg
Saved ../dataset
Saved ../dataset/test/jerson/2019-06-18 23:10:02.218820

Saved ../dataset
Saved ../dataset/test/angel/2019-06-18 23:10:07.9360132019-06-18 23:18:07.689725__.jpg
Saved ../dataset
Saved ../dataset/test/angel/2019-06-18 23:10:07.8570882019-06-18 23:18:07.724824__.jpg
Saved ../dataset
Saved ../dataset/test/angel/2019-06-18 23:10:11.0707732019-06-18 23:18:07.738356__.jpg
Saved ../dataset
Saved ../dataset/test/angel/2019-06-18 23:10:05.5979892019-06-18 23:18:07.751807__.jpg
Saved ../dataset
Saved ../dataset/test/angel/2019-06-18 23:10:08.1355342019-06-18 23:18:07.784267__.jpg
Saved ../dataset
Saved ../dataset/test/angel/2019-06-18 23:10:08.7817232019-06-18 23:18:07.819723__.jpg
Saved ../dataset
Saved ../dataset/test/angel/2019-06-18 23:10:10.1429442019-06-18 23:18:07.853282__.jpg
Saved ../dataset
Saved ../dataset/test/angel/2019-06-18 23:10:06.4233982019-06-18 23:18:07.865908__.jpg
Saved ../dataset
Saved ../dataset/test/angel/2019-06-18 23:10:05.6356952019-06-18 23:18:07.878829__.jpg
Saved ../dataset
Saved ../dataset/test/angel/2019-06-18 23:10:10

In [3]:
from cactus.utils.image import crop_and_save, crop_Image_rect

In [4]:
jerson = faces[0]

In [5]:
jerson

[['../framess/jerson/2019-06-18 16:26:15.343584.jpg',
  '../salidas/jerson/2019-06-18 16:26:15.343584.jpg',
  '../salidas/train/jerson/2019-06-18 16:26:15.343584.jpg',
  '../salidas/test/jerson/2019-06-18 16:26:15.343584.jpg',
  array([ 43, 188, 213, 425])],
 ['../framess/jerson/2019-06-18 16:26:16.102665.jpg',
  '../salidas/jerson/2019-06-18 16:26:16.102665.jpg',
  '../salidas/train/jerson/2019-06-18 16:26:16.102665.jpg',
  '../salidas/test/jerson/2019-06-18 16:26:16.102665.jpg',
  array([ 90, 132, 328, 519])],
 ['../framess/jerson/2019-06-18 16:26:16.102665.jpg',
  '../salidas/jerson/2019-06-18 16:26:16.102665.jpg',
  '../salidas/train/jerson/2019-06-18 16:26:16.102665.jpg',
  '../salidas/test/jerson/2019-06-18 16:26:16.102665.jpg',
  array([217, 359, 453, 735])],
 ['../framess/jerson/2019-06-18 16:26:15.052833.jpg',
  '../salidas/jerson/2019-06-18 16:26:15.052833.jpg',
  '../salidas/train/jerson/2019-06-18 16:26:15.052833.jpg',
  '../salidas/test/jerson/2019-06-18 16:26:15.052833.jp

In [9]:
"../framess/jerson/2019-06-18 16:26:15.343584.jpg".replace("framess","outp")

'../outp/jerson/2019-06-18 16:26:15.343584.jpg'

In [6]:
from cactus.utils.folder import get_info

In [7]:
from cactus.processing  import video

In [8]:
video.folder_to_frames("../frame")

../frame


[('../frame', 'Jerson', []),
 ('../frame',
  'Martin',
  ['2019-05-13 10:38:50.282629.jpg',
   '2019-05-13 10:38:50.435755.jpg',
   '2019-05-13 10:38:49.961869.jpg',
   '2019-05-13 10:38:51.629608.jpg',
   '2019-05-13 10:38:50.125851.jpg'])]

Using haar method


In [6]:
img1 = "../frame/2019-05-13 10:38:49.961869.jpg"
img2 = "../frame/2019-05-13 10:38:50.125851.jpg"
img3 = "../frame/2019-05-13 10:38:50.282629.jpg"

hawking = "../src/hawkingt-stephen-hawking-june-2004.jpg"
feynman = "../src/feynman.jpeg"
bigbang = "../src/thebigbang.jpg"
bigbang2 = "../src/bigbang2.jpg"

In [7]:
b1 = dnn_detector.detect(img1)
b2 = dnn_detector.detect(img2)
b3 = dnn_detector.detect(img3)

bh = dnn_detector.detect(hawking)
bf = dnn_detector.detect(feynman)

In [8]:
boxes = dnn_detector.get_boxes_from_directory([img1,img2,img3, hawking,bigbang,bigbang2, feynman])

In [16]:
boxes[5]

[['../src/bigbang2.jpg', array([189.3,  40.3, 264.7, 115.7])],
 ['../src/bigbang2.jpg', array([242.6,  79.6, 315.4, 152.4])],
 ['../src/bigbang2.jpg', array([129.8, 101.8, 218.2, 190.2])],
 ['../src/bigbang2.jpg', array([443.95,  61.95, 531.05, 149.05])],
 ['../src/bigbang2.jpg', array([ 77.9,  89.9, 148.1, 160.1])],
 ['../src/bigbang2.jpg', array([343.65,  99.65, 433.35, 189.35])],
 ['../src/bigbang2.jpg', array([465.05, 180.05, 559.95, 274.95])]]

In [17]:
from cactus.utils import folder

In [32]:
dir("../frame")

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

In [22]:
raiz = folder.get_folders("../cactus/face")

An error occured


TypeError: 'NoneType' object is not subscriptable

In [24]:
dnn_detector.get_boxes_from_directory("../frames")

IsADirectoryError: [Errno 21] Is a directory: '.'

In [19]:
frames = "../cactus/face"
dest = "faces"
for nodo in raiz:
    nodo_total = "{}/{}".format(frames, nodo)
    nodo_destino = "{}/{}".format(dest, nodo)
    
    archivos = folder.get_files(nodo_total)
    archivos = list(map(lambda x:["{}/{}".format(nodo_total,x),"{}/{}".format(nodo_destino,x)] , archivos))
    print(archivos)

[['../cactus/face/strategy/haar.py', 'faces/strategy/haar.py'], ['../cactus/face/strategy/dnn.py', 'faces/strategy/dnn.py'], ['../cactus/face/strategy/__init__.py', 'faces/strategy/__init__.py'], ['../cactus/face/strategy/hog.py', 'faces/strategy/hog.py']]
[['../cactus/face/__pycache__/detection.cpython-36.pyc', 'faces/__pycache__/detection.cpython-36.pyc'], ['../cactus/face/__pycache__/__init__.cpython-36.pyc', 'faces/__pycache__/__init__.cpython-36.pyc']]
