In [1]:
import sys
sys.path.append("..")
import cv2
import numpy as np
from cactus.face.detection import detector
dnn_detector = detector("haar")
faces = dnn_detector.to_face("../framess", "salidas")

Using haar method
Detecting manu's faces
Detecting martin's faces
Detecting jerson's faces
Detecting angel's faces
Detecting cristian's faces
Detecting frank's faces


In [4]:
faces[0]

[[['../framess/manu/2019-06-13 21:34:40.693878.jpg',
   array([  5.85, 142.85, 345.15, 482.15])]],
 [['../framess/manu/2019-06-13 21:34:40.022991.jpg',
   array([-19.2, 328.8, 303.2, 651.2])]],
 [],
 [],
 [],
 [],
 [],
 [['../framess/manu/2019-06-13 21:34:40.093585.jpg',
   array([-14.6,  38.4, 302.6, 355.6])]],
 [['../framess/manu/2019-06-13 21:34:40.276795.jpg',
   array([-18.3, 144.7, 296.3, 459.3])]],
 [],
 [],
 [['../framess/manu/2019-06-13 21:34:39.902163.jpg',
   array([  2., 130., 370., 498.])]],
 [['../framess/manu/2019-06-13 21:34:40.223022.jpg',
   array([ 48., 177., 360., 489.])]],
 [['../framess/manu/2019-06-13 21:34:40.298924.jpg',
   array([ 60.75, 196.75, 314.25, 450.25])]],
 [],
 [['../framess/manu/2019-06-13 21:34:40.445990.jpg',
   array([  1.15, 226.15, 285.85, 510.85])]],
 [['../framess/manu/2019-06-13 21:34:39.933879.jpg',
   array([  2., 130., 370., 498.])]],
 [],
 [],
 [['../framess/manu/2019-06-13 21:34:40.666855.jpg',
   array([-20.3, 135.7, 320.3, 476.3])]],


In [3]:
from PIL import Image


In [4]:
from cactus.processing.video import to_frames, folder_to_frames
#to_frames('../videos/Lab/Prueba_Martin - Ingenieria 21-316.avi', '../frame',1)


In [5]:
folder_to_frames("../videos/", "../framess")

Transfor to frame manu videos
Transfor to frame manu videos
Transfor to frame manu videos
Transfor to frame martin videos
Transfor to frame martin videos
Transfor to frame martin videos
Transfor to frame jerson videos
Transfor to frame jerson videos
Transfor to frame jerson videos
Transfor to frame angel videos
Transfor to frame angel videos
Transfor to frame angel videos
Transfor to frame Lab videos
Transfor to frame Lab videos
Transfor to frame cristian videos
Transfor to frame frank videos


True

In [6]:
from cactus.utils.folder import get_info

In [7]:
from cactus.processing  import video

In [8]:
video.folder_to_frames("../frame")

../frame


[('../frame', 'Jerson', []),
 ('../frame',
  'Martin',
  ['2019-05-13 10:38:50.282629.jpg',
   '2019-05-13 10:38:50.435755.jpg',
   '2019-05-13 10:38:49.961869.jpg',
   '2019-05-13 10:38:51.629608.jpg',
   '2019-05-13 10:38:50.125851.jpg'])]

Using haar method


FileNotFoundError: [Errno 2] No such file or directory: '2019-06-13 21:34:40.693878.jpg'

In [6]:
img1 = "../frame/2019-05-13 10:38:49.961869.jpg"
img2 = "../frame/2019-05-13 10:38:50.125851.jpg"
img3 = "../frame/2019-05-13 10:38:50.282629.jpg"

hawking = "../src/hawkingt-stephen-hawking-june-2004.jpg"
feynman = "../src/feynman.jpeg"
bigbang = "../src/thebigbang.jpg"
bigbang2 = "../src/bigbang2.jpg"

In [7]:
b1 = dnn_detector.detect(img1)
b2 = dnn_detector.detect(img2)
b3 = dnn_detector.detect(img3)

bh = dnn_detector.detect(hawking)
bf = dnn_detector.detect(feynman)

In [8]:
boxes = dnn_detector.get_boxes_from_directory([img1,img2,img3, hawking,bigbang,bigbang2, feynman])

In [16]:
boxes[5]

[['../src/bigbang2.jpg', array([189.3,  40.3, 264.7, 115.7])],
 ['../src/bigbang2.jpg', array([242.6,  79.6, 315.4, 152.4])],
 ['../src/bigbang2.jpg', array([129.8, 101.8, 218.2, 190.2])],
 ['../src/bigbang2.jpg', array([443.95,  61.95, 531.05, 149.05])],
 ['../src/bigbang2.jpg', array([ 77.9,  89.9, 148.1, 160.1])],
 ['../src/bigbang2.jpg', array([343.65,  99.65, 433.35, 189.35])],
 ['../src/bigbang2.jpg', array([465.05, 180.05, 559.95, 274.95])]]

In [17]:
from cactus.utils import folder

In [32]:
dir("../frame")

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

In [22]:
raiz = folder.get_folders("../cactus/face")

An error occured


TypeError: 'NoneType' object is not subscriptable

In [24]:
dnn_detector.get_boxes_from_directory("../frames")

IsADirectoryError: [Errno 21] Is a directory: '.'

In [19]:
frames = "../cactus/face"
dest = "faces"
for nodo in raiz:
    nodo_total = "{}/{}".format(frames, nodo)
    nodo_destino = "{}/{}".format(dest, nodo)
    
    archivos = folder.get_files(nodo_total)
    archivos = list(map(lambda x:["{}/{}".format(nodo_total,x),"{}/{}".format(nodo_destino,x)] , archivos))
    print(archivos)

[['../cactus/face/strategy/haar.py', 'faces/strategy/haar.py'], ['../cactus/face/strategy/dnn.py', 'faces/strategy/dnn.py'], ['../cactus/face/strategy/__init__.py', 'faces/strategy/__init__.py'], ['../cactus/face/strategy/hog.py', 'faces/strategy/hog.py']]
[['../cactus/face/__pycache__/detection.cpython-36.pyc', 'faces/__pycache__/detection.cpython-36.pyc'], ['../cactus/face/__pycache__/__init__.cpython-36.pyc', 'faces/__pycache__/__init__.cpython-36.pyc']]
